### ISSUE TITLE
Flashcard download broken

### ISSUE THREAD

**Issue by Ghabry** [abesto/duolingo-to-anki#9] opened 2015-05-08 01:08 UTC
Since a few days the flashcard URL returns no cards at all.

```
https://www.duolingo.com/api/1/flashcards?n=10000&allow_partial_deck=true
```

Passing a smaller value to n, for me the highest possible is 135 (I have 146 words) works. But this won't list all recently learned vocabs :/

**Comment by abesto** [comment] 2015-05-08 04:45
Thanks for opening an issue to track this!

This is indeed a problem, I've confirmed it with at least another user. I've reported the problem to Duolingo a few weeks ago, no response so far. My current best idea is to revert to another API (https://github.com/abesto/duolingo-to-anki/commit/3db970567779a1357835cab91e5d7c6d312b4bd6 switched to the flashcards API).

Pull requests welcome, of course. Unfortunately I can't commit to a fix date because life :(

**Comment by Ghabry** [comment] 2015-05-08 11:59
Thx for the response. Yeah I can try on my own to fix this. I like Anki much more then this "Words" flashcard feature of Duolingo.

Just a few questions then:
1. Where does your program fetch all that vocabulary from?

E.g. for `almuerzo` Anki contains

```
lunch
(I) have lunch
(I) have … for lunch
[...]
```

(and many more)

From which URL are these translations downloaded? I couldn't really figure this out by just looking at the sourcecode.

2.
Which IDE are you using for Scala? I have to set up a dev environment, never used Scala before.

**Comment by abesto** [comment] 2015-05-08 12:21
The entry-point for fetching words is https://github.com/abesto/duolingo-to-anki/blob/master/src/main/scala/net/abesto/duolingotoanki/Main.scala#L53-L56. `DuolingoFlashcardScraper` takes care of fetching data from the flashcard API. Then `DuolingoVocabularyScraper` apparently fetches metadata about the words to add for tags, but I'm a bit hazy on the details there. `translators.DuolingoToAnki` merges the two into a data format that will be used by `AnkiExporter`.

The URLs used and other constants can be found in `Constants.scala`.

The app used to use a different API, but it took some extra legwork to get a list of word-pairs from that; https://github.com/abesto/duolingo-to-anki/commit/3db970567779a1357835cab91e5d7c6d312b4bd6 is the commit that switched to the flashcards API.

For development I use [IntelliJ IDEA](https://www.jetbrains.com/idea/), it has a free and open-source edition that includes support for Scala.

**Comment by abesto** [comment] 2015-05-17 21:05
I've found a workaround using another API. Before I close this, please check out this release: https://github.com/abesto/duolingo-to-anki/releases/tag/v0.2.4

**Closed as completed** 2015-05-20 09:37 UTC
Labels: bug
